language: java
sudo: false

jdk:
  - oraclejdk8

os:
  - linux

script:
  - cd ./google-code-jam
  - mvn --batch-mode --quiet verify
  - cd  ../programming-challenges
  - mvn --batch-mode --quiet verify
